# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2036b2a0caf86a0fcbd7e43071f023b"
name = "remix-shop-test"
handle = "remix-shop-test"
application_url = "https://624a-103-197-204-22.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testnext-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://624a-103-197-204-22.ngrok-free.app/auth/callback",
  "https://624a-103-197-204-22.ngrok-free.app/auth/shopify/callback",
  "https://624a-103-197-204-22.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
